### ISSUE TITLE
Not displayed list of birthdays in the calendar

### ISSUE THREAD

**Issue by thfree** [owncloud/calendar#824]
Do not display birthdays on the calendar after upgrading to 8.1.0
Versions:
   owncloud-8.1.0RC2
   contacts-8.1.0RC2
   calendar-8.1.0RC2

**Comment by MeCias** [comment]
I can confirm this behaviour for the 8.1 final as well.

Also the birthday caldav links is not working no more:

http://owncloud.domain.com/remote.php/caldav/calendars/User/contact_birthdays

**Comment by thfree** [comment]
ownCloud 8.1.0 (daily)
Build:2015-07-02T22:33:50+00:00 06ec916b1128b9a1ec79751bdd78cc4a8c64ace8
contacts 8.1.0
calendar 8.1.0

The situation has not changed

**Comment by georgehrke** [comment]
here is a fix: https://github.com/owncloud/contacts/pull/970

**Comment by MeCias** [comment]
Hi and thanks a lot.

I can confirm that the fix is working in owncloud. The birthdays are getting displayed again.

The caldav link seems to be still not functional though.

http://owncloud.domain.com/remote.php/caldav/calendars/User/contact_birthdays

**Comment by georgehrke** [comment]
Browsing caldav via web browser got disabled. Please validate that you can't access the birthday calendar in a proper desktop calendar client.

**Comment by MeCias** [comment]
Yes I know. I can not access the birthdays via Thunderbird or the calddav-sync App for Android.
Thunderbird is not doing anything and the caldav-sync App is at least seeing the Birthday Calendar but is not pulling anything from it.

**Comment by MeCias** [comment]
Maybe this is related

Exception: {"Message":"HTTP\/1.1 403 User did not have the required privileges ({DAV:}read) for path \"calendars\/Michael\/contact_birthdays\"","Code":0,"Trace":"#0 \/var\/www\/vhosts\/web\/httpdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAVACL\/Plugin.php(769): Sabre\\DAVACL\\Plugin->checkPrivileges('calendars\/M...', '{DAV:}read')\n#1 [internal function]: Sabre\\DAVACL\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#2 \/var\/www\/vhosts\/web\/httpdocs\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#3 \/var\/www\/vhosts\/web\/httpdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#4 \/var\/www\/vhosts\/web\/httpdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 \/var\/www\/vhosts\/web\/httpdocs\/owncloud\/apps\/calendar\/appinfo\/remote.php(57): Sabre\\DAV\\Server->exec()\n#6 \/var\/www\/vhosts\/web\/httpdocs\/owncloud\/remote.php(132): require_once('\/var\/www\/vhosts...')\n#7 {main}","File":"\/var\/www\/vhosts\/web\/httpdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAVACL\/Plugin.php","Line":223}

**Comment by georgehrke** [comment]
can you modify some contacts please. This will increase the ctag and tell thunderbird, that something changed.

**Comment by georgehrke** [comment]
that looks indeed related, I'll check, thanks

**Comment by MeCias** [comment]
Just in case I also added a few test contacts with birthdays. Had no effect.

Thanks for your help

**Comment by georgehrke** [comment]
@MeCias The privilege issue itself should be fixed with v0.7.1. You still need the patched contacts app tough. Would be great if you could verify, so we can close this issue, thx :)

**Comment by raimund-schluessler** [comment]
Birthdays are shown again with calendar v0.7.1 and https://github.com/owncloud/contacts/pull/970

**Comment by georgehrke** [comment]
thx a lot for verifying :)

**Comment by MeCias** [comment]
HI,

Thanks again

The birthdays in the calendar app are still displayed after the fix for 4.0.0, but unfortunately the link is still not working as it used to be.

 The Error message as I posted yesterday is gone, now there is something new. Not sure if related because the contacts app is not mentioned but a permission issue is again shown in the log file

Exception: {"Exception":"ErrorException","Message":"session_start(): ps_files_cleanup_dir: opendir(\/var\/lib\/php\/session) failed: Permission denied (13)","Code":0,"Trace":"#0 [internal function]: OC\\Session\\Internal->trapError(8, 'session_start()...', '\/var\/www\/vhosts...', 38, Array)\n#1 \/var\/www\/vhosts\/web\/httpdocs\/owncloud\/lib\/private\/session\/internal.php(38): session_start()\n#2 \/var\/www\/vhosts\/web\/httpdocs\/owncloud\/lib\/base.php(454): OC\\Session\\Internal->__construct('51888fdf6a8fa')\n#3 \/var\/www\/vhosts\/web\/httpdocs\/owncloud\/lib\/base.php(594): OC::initSession()\n#4 \/var\/www\/vhosts\/web\/httpdocs\/owncloud\/lib\/base.php(1115): OC::init()\n#5 \/var\/www\/vhosts\/web\/httpdocs\/owncloud\/index.php(38): require_once('\/var\/www\/vhosts...')\n#6 {main}","File":"\/var\/www\/vhosts\/web\/httpdocs\/owncloud\/lib\/private\/session\/internal.php","Line":104}

**Comment by georgehrke** [comment]
`session_start() [...] Permission denied` looks a lot like a configuration error on your side. I'll try to reproduce it.

**Comment by georgehrke** [comment]
please see http://stackoverflow.com/a/2952173

**Comment by MeCias** [comment]
I'll have a look. Thanks

**Comment by dances-with-clouds** [comment]
I am sorry that I have to tell you that the above mentioned patch does not work at my place: I just upgraded from OC 8.0.4 to 8.1 and now Thunderbird can't synchronise the contacts' birthdays and when I log on to OC web UI, the contact app doesn't load properly.

**Comment by raimund-schluessler** [comment]
Are you using the latest version of the contacts app with the patch https://github.com/owncloud/contacts/pull/970 (which was merged this morning) and v0.7.1 of the calendar app? For me birthdays are synced and shown in the web interface with this versions.

**Comment by dances-with-clouds** [comment]
Yes and yes. :) The line  "$vCal->add($vEvent);" is present in contact.php and OC's GUI tells me:
"Calendar 0.7.1 von Georg Ehrke, Bart Visscher, Jakob Sack (AGPL-Lizenziert)". But still the birthday calendar is not working and the contact GUI app doesn't load properly: it never stops loading.

**Comment by georgehrke** [comment]
@dances-with-clouds Do you see anything else in the logs. If yes, please file a new bug report using the issue template.

**Comment by dances-with-clouds** [comment]
No, the web server (lighttpd) doesn't complain about anything. I will downgrade to 8.0x again and wait for version 8.1.1, which will be free of this error... hopefully. ;)

**Comment by georgehrke** [comment]
is there anything in the ownCloud.log?

**Comment by dances-with-clouds** [comment]
Silly me! :)

Yes, there is an issue in the OC log:

Exception: {"Exception":"Exception","Message":"Freigabe-Backend f\u00fcr contact nicht gefunden","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/tags.php(129): OC\\Share\\Share::getBackend('contact')\n#1 \/var\/www\/owncloud\/lib\/private\/tagmanager.php(88): OC\\Tags->__construct(Object(OC\\Tagging\\TagMapper), 'admin', 'contact', Array, true)\n#2 \/var\/www\/owncloud\/apps\/contacts\/lib\/dispatcher.php(92): OC\\TagManager->load('contact', Array, true)\n#3 \/var\/www\/owncloud\/3rdparty\/pimple\/pimple\/src\/Pimple\/Container.php(112): OCA\\Contacts\\Dispatcher->OCA\\Contacts\\{closure}(Object(OC\\AppFramework\\DependencyInjection\\DIContainer))\n#4 \/var\/www\/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php(96): Pimple\\Container->offsetGet('GroupController')\n#5 \/var\/www\/owncloud\/lib\/private\/appframework\/app.php(92): OC\\AppFramework\\Utility\\SimpleContainer->query('GroupController')\n#6 \/var\/www\/owncloud\/lib\/public\/appframework\/app.php(134): OC\\AppFramework\\App::main('GroupController', 'getGroups', Object(OC\\AppFramework\\DependencyInjection\\DIContainer))\n#7 \/var\/www\/owncloud\/apps\/contacts\/appinfo\/routes.php(385): OCP\\AppFramework\\App->dispatch('GroupController', 'getGroups')\n#8 [internal function]: OC\\Route\\Router->OCA\\Contacts\\{closure}(Array)\n#9 \/var\/www\/owncloud\/lib\/private\/route\/router.php(274): call_user_func(Object(Closure), Array)\n#10 \/var\/www\/owncloud\/lib\/base.php(867): OC\\Route\\Router->match('\/apps\/contacts\/...')\n#11 \/var\/www\/owncloud\/index.php(40): OC::handleRequest()\n#12 {main}","File":"\/var\/www\/owncloud\/lib\/private\/share\/share.php","Line":1357}

**Comment by georgehrke** [comment]
That looks like a bug in the contacts app. Please report a bug in [contacts repo](http://github.com/owncloud/contacts) using the [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md)
